CXX = g++
CXXFLAGS = -std=c++11 -Wall -Wextra

SOURCES = main.cpp \
          Instagram340.cpp \
          User.cpp \
          Post.cpp \
          Reel.cpp \
          Story.cpp \
          Node.cpp \
          LinkedBag.cpp

OBJECTS = $(SOURCES:.cpp=.o)
TARGET = instagram340

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJECTS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $<

clean:
	rm -f $(OBJECTS) $(TARGET)
